version: '3'
services:
  db:
    image: mysql:8.0
    container_name: personal_planner_mariadb
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: personal_planner_backend
    command: sh -c "python3 ./personal_planner/manage.py migrate --noinput && python3 ./personal_planner/manage.py collectstatic --noinput && python ./personal_planner/manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/personal_planner
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data:
